/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV;

import QLTV.helpers.ShareData;
import QLTV.model.ThongTinSach;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author ngohien
 */
public class MainForm extends javax.swing.JFrame {
    private QuanLyDocGia mQuanlydocgia;
    private QuanLyKhoSach mQuanlysach;
    private QLMuonTraSach mQLmuontrasach; 
    private QuanLyViPham mQuanlyvipham;
    private TheDocGia mThedocgia;
    private TTSach mThongtinsach;
    private DsSach mDanhsachSach;
    private PhieuMuonSach mPhieumuonsach;
    private PhieuTraSach mPhieutrasach;
    private PhieuPhat mPhieuphat;       
    private BaoCao mBaocaomuon;
      
            
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        
        
    }
    public void removeTabAt (int index){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDocGia = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnThongTinSach = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnDsSach = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnMuonSach = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnTraSach = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnPhieuPhat = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnBaoCao = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        tplMainBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuQuanLySach = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuQuanLyDocGia = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuQLMuonTra = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mnuQLViPham = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuTheDocGia = new javax.swing.JMenuItem();
        mnuTTSach = new javax.swing.JMenuItem();
        mnuDsSach = new javax.swing.JMenuItem();
        mnuPhieuMuon = new javax.swing.JMenuItem();
        mnuPhieuTra = new javax.swing.JMenuItem();
        mnuPhieuThu = new javax.swing.JMenuItem();
        mnuBaoCao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Student-id-icon32.png"))); // NOI18N
        btnDocGia.setText("Thẻ Độc Giả");
        btnDocGia.setFocusable(false);
        btnDocGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocGia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDocGia);
        jToolBar1.add(jSeparator4);

        btnThongTinSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tiepnhansach32.png"))); // NOI18N
        btnThongTinSach.setText("Thông Tin sách");
        btnThongTinSach.setFocusable(false);
        btnThongTinSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongTinSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongTinSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongTinSach);
        jToolBar1.add(jSeparator5);

        btnDsSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tracuu32.png"))); // NOI18N
        btnDsSach.setText("Danh sách Sách");
        btnDsSach.setFocusable(false);
        btnDsSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDsSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDsSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDsSach);
        jToolBar1.add(jSeparator6);

        btnMuonSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Books-2-icon33.png"))); // NOI18N
        btnMuonSach.setText("Mượn Sách");
        btnMuonSach.setFocusable(false);
        btnMuonSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMuonSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMuonSach);
        jToolBar1.add(jSeparator7);

        btnTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/phieuphat32.png"))); // NOI18N
        btnTraSach.setText("Trả Sách");
        btnTraSach.setFocusable(false);
        btnTraSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTraSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTraSach);
        jToolBar1.add(jSeparator8);

        btnPhieuPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sales-report-icon.png"))); // NOI18N
        btnPhieuPhat.setText("Phiếu phạt");
        btnPhieuPhat.setFocusable(false);
        btnPhieuPhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPhieuPhat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPhieuPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuPhatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPhieuPhat);
        jToolBar1.add(jSeparator12);

        btnBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baocao32.png"))); // NOI18N
        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.setFocusable(false);
        btnBaoCao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaoCao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBaoCao);
        jToolBar1.add(jSeparator9);

        tbrAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trogiup32.png"))); // NOI18N
        tbrAboutUs.setText("Giới Thiệu");
        tbrAboutUs.setFocusable(false);
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);

        tplMainBoard.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tplMainBoardAncestorRemoved(evt);
            }
        });

        lblLoginName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRole.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(lblLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Hệ thống");

        mnuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        mnuDangXuat.setText("Đăng xuất");
        mnuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDangXuat);
        jMenu1.add(jSeparator1);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon-16.png"))); // NOI18N
        mnuExit.setText("Thoát");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mnuQuanLySach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQuanLySach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book1.png"))); // NOI18N
        mnuQuanLySach.setText("Quản Lý Kho Sách");
        mnuQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLySachActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQuanLySach);
        jMenu2.add(jSeparator2);

        mnuQuanLyDocGia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQuanLyDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"))); // NOI18N
        mnuQuanLyDocGia.setText("Quản Lý Độc Giả");
        mnuQuanLyDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQuanLyDocGiaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQuanLyDocGia);
        jMenu2.add(jSeparator10);

        mnuQLMuonTra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQLMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books-icon16.png"))); // NOI18N
        mnuQLMuonTra.setText("Quản Lý Mượn Trả Sách");
        mnuQLMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLMuonTraActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQLMuonTra);
        jMenu2.add(jSeparator11);

        mnuQLViPham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuQLViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vipham16.png"))); // NOI18N
        mnuQLViPham.setText("Quản Lý Vi Phạm");
        mnuQLViPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuQLViPhamActionPerformed(evt);
            }
        });
        jMenu2.add(mnuQLViPham);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Biểu mẫu");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        mnuTheDocGia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuTheDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/thedocgia16.png"))); // NOI18N
        mnuTheDocGia.setText("Thẻ Độc Giả");
        mnuTheDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTheDocGiaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuTheDocGia);

        mnuTTSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuTTSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/thongtinsach16.png"))); // NOI18N
        mnuTTSach.setText("Thông tin sách");
        mnuTTSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTTSachActionPerformed(evt);
            }
        });
        jMenu4.add(mnuTTSach);

        mnuDsSach.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuDsSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/books-icon16.png"))); // NOI18N
        mnuDsSach.setText(" Danh sách Sách");
        mnuDsSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDsSachActionPerformed(evt);
            }
        });
        jMenu4.add(mnuDsSach);

        mnuPhieuMuon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/muonsach16.png"))); // NOI18N
        mnuPhieuMuon.setText("Phiếu mượn sách");
        mnuPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPhieuMuonActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPhieuMuon);

        mnuPhieuTra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuPhieuTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trasach16.png"))); // NOI18N
        mnuPhieuTra.setText("Phiếu trả sách");
        mnuPhieuTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPhieuTraActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPhieuTra);

        mnuPhieuThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuPhieuThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/vipham16.png"))); // NOI18N
        mnuPhieuThu.setText("Phiếu thu tiền phạt");
        mnuPhieuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPhieuThuActionPerformed(evt);
            }
        });
        jMenu4.add(mnuPhieuThu);

        mnuBaoCao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baocao1_16.png"))); // NOI18N
        mnuBaoCao.setText("Báo cáo mượn");
        mnuBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBaoCaoActionPerformed(evt);
            }
        });
        jMenu4.add(mnuBaoCao);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Giới thiệu");
        jMenu3.add(jSeparator3);

        mnuAboutUS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAboutUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trogiup16.png"))); // NOI18N
        mnuAboutUS.setText("Giới thiệu");
        mnuAboutUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUSActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAboutUS);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tplMainBoard)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tplMainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLySachActionPerformed

        if(mQuanlysach==null){
            mQuanlysach = new QuanLyKhoSach();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icons/book1.png"));
            tplMainBoard.addTab("Quản Lý Kho Sách", icon,mQuanlysach,"Quản lý kho sách");        
        }
        tplMainBoard.setSelectedComponent(mQuanlysach);
    }//GEN-LAST:event_mnuQuanLySachActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        mnuTheDocGiaActionPerformed(evt);
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuQuanLyDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQuanLyDocGiaActionPerformed
        if(mQuanlydocgia==null){
        mQuanlydocgia = new QuanLyDocGia();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/10207-man-student-light-skin-tone-icon-16.png"));
        tplMainBoard.addTab("Quản Lý Độc Giả", icon,mQuanlydocgia,"Quản lý độc giả");
        }
        tplMainBoard.setSelectedComponent(mQuanlydocgia);
        
        
    }//GEN-LAST:event_mnuQuanLyDocGiaActionPerformed

    private void mnuQLMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLMuonTraActionPerformed
        if(mQLmuontrasach==null){
        mQLmuontrasach = new QLMuonTraSach();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/books-icon16.png"));
        tplMainBoard.addTab("Quản Lý Mượn Trả Sách", icon,mQLmuontrasach,"Quản lý mượn trả sách");
        }
        tplMainBoard.setSelectedComponent(mQLmuontrasach);        
    }//GEN-LAST:event_mnuQLMuonTraActionPerformed

    private void mnuQLViPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuQLViPhamActionPerformed
        if(mQuanlyvipham==null){
        mQuanlyvipham = new QuanLyViPham();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/vipham16.png"));
        tplMainBoard.addTab("Quản Lý Vi Phạm", icon,mQuanlyvipham,"Quản lý vi phạm");
        }
        tplMainBoard.setSelectedComponent(mQuanlyvipham);  
    }//GEN-LAST:event_mnuQLViPhamActionPerformed

    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        AboutusDialog aboutDialog = new AboutusDialog(this, true);
        
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_tbrAboutUsActionPerformed

    private void mnuAboutUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUSActionPerformed
        tbrAboutUsActionPerformed(evt);
    }//GEN-LAST:event_mnuAboutUSActionPerformed

    private void mnuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDangXuatActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        
        loginDialog.setVisible(true);
        
        processLoginSuccessful();
    }//GEN-LAST:event_mnuDangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
        
        processLoginSuccessful();
    }//GEN-LAST:event_formWindowOpened

    private void mnuPhieuTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPhieuTraActionPerformed
        if(mPhieutrasach==null){
        mPhieutrasach = new PhieuTraSach();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/trasach16.png"));
        tplMainBoard.addTab("Phiếu Trả Sách", icon,mPhieutrasach,"Phiếu trả sách");
        }
        tplMainBoard.setSelectedComponent(mPhieutrasach);         
    }//GEN-LAST:event_mnuPhieuTraActionPerformed

    private void mnuPhieuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPhieuThuActionPerformed
        if(mPhieuphat==null){
        mPhieuphat = new PhieuPhat();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/vipham16.png"));
        tplMainBoard.addTab("Phiếu Thu Tiền Phạt", icon,mPhieuphat,"Phiếu thu tiền phạt");
        }
        tplMainBoard.setSelectedComponent(mPhieuphat);          
    }//GEN-LAST:event_mnuPhieuThuActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void mnuTheDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTheDocGiaActionPerformed
        if(mThedocgia==null){
        mThedocgia = new TheDocGia();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/thedocgia16.png"));
        tplMainBoard.addTab("Thẻ Độc Giả", icon,mThedocgia,"Thẻ độc giả");
        }
        tplMainBoard.setSelectedComponent(mThedocgia);  
       
    }//GEN-LAST:event_mnuTheDocGiaActionPerformed

    private void mnuDsSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDsSachActionPerformed
        if(mDanhsachSach==null){
        mDanhsachSach = new DsSach();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/books-icon16.png"));
        tplMainBoard.addTab("Danh sách Sách", icon,mDanhsachSach,"Danh sách Sách");
        }
        tplMainBoard.setSelectedComponent(mDanhsachSach);
    }//GEN-LAST:event_mnuDsSachActionPerformed

    private void mnuTTSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTTSachActionPerformed
        if(mThongtinsach==null){
        mThongtinsach = new TTSach();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/thongtinsach16.png"));
        tplMainBoard.addTab("Thông Tin Sách", icon,mThongtinsach,"Thông tin sách");
        }
        tplMainBoard.setSelectedComponent(mThongtinsach); 
    }//GEN-LAST:event_mnuTTSachActionPerformed

    private void tplMainBoardAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tplMainBoardAncestorRemoved
        
    }//GEN-LAST:event_tplMainBoardAncestorRemoved

    private void mnuPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPhieuMuonActionPerformed
        if(mPhieumuonsach==null){
        mPhieumuonsach = new PhieuMuonSach();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/muonsach16.png"));
        tplMainBoard.addTab("Phiếu Mượn Sách", icon,mPhieumuonsach,"Phiếu mượn sách");
        }
        tplMainBoard.setSelectedComponent(mPhieumuonsach);
    }//GEN-LAST:event_mnuPhieuMuonActionPerformed

    private void mnuBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBaoCaoActionPerformed
        if(mBaocaomuon==null){
        mBaocaomuon = new BaoCao();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icons/baocao1_16.png"));
        tplMainBoard.addTab("Báo Cáo ", icon,mBaocaomuon,"Báo cáo ");
        }
        tplMainBoard.setSelectedComponent(mBaocaomuon);        
    }//GEN-LAST:event_mnuBaoCaoActionPerformed

    private void btnThongTinSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinSachActionPerformed
        mnuTTSachActionPerformed(evt);
    }//GEN-LAST:event_btnThongTinSachActionPerformed

    private void btnDsSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsSachActionPerformed
        mnuDsSachActionPerformed(evt);
    }//GEN-LAST:event_btnDsSachActionPerformed

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
        mnuPhieuMuonActionPerformed(evt);
    }//GEN-LAST:event_btnMuonSachActionPerformed

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        mnuPhieuTraActionPerformed(evt);
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnPhieuPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuPhatActionPerformed
        mnuPhieuThuActionPerformed(evt);
    }//GEN-LAST:event_btnPhieuPhatActionPerformed

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        mnuBaoCaoActionPerformed(evt);
    }//GEN-LAST:event_btnBaoCaoActionPerformed
    
    private void processLoginSuccessful(){
        lblLoginName.setText(ShareData.nguoiDangNhap.getTenDangNhap());
        lblRole.setText(ShareData.nguoiDangNhap.getVaiTro() );
        tplMainBoard.removeAll();
        if(ShareData.nguoiDangNhap.getVaiTro().equals("Độc giả")){
            mnuQuanLyDocGia.setEnabled(false);
            mnuQuanLySach.setEnabled(false);
            mnuQLMuonTra.setEnabled(false);
            mnuQLViPham.setEnabled(false);
            
        }else if(ShareData.nguoiDangNhap.getVaiTro().equals("admin")){
            mnuQuanLyDocGia.setEnabled(true);
            mnuQuanLySach.setEnabled(true);
            mnuQLMuonTra.setEnabled(true);
            mnuQLViPham.setEnabled(true); 
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCao;
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnDsSach;
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnPhieuPhat;
    private javax.swing.JButton btnThongTinSach;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JMenuItem mnuAboutUS;
    private javax.swing.JMenuItem mnuBaoCao;
    private javax.swing.JMenuItem mnuDangXuat;
    private javax.swing.JMenuItem mnuDsSach;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuPhieuMuon;
    private javax.swing.JMenuItem mnuPhieuThu;
    private javax.swing.JMenuItem mnuPhieuTra;
    private javax.swing.JMenuItem mnuQLMuonTra;
    private javax.swing.JMenuItem mnuQLViPham;
    private javax.swing.JMenuItem mnuQuanLyDocGia;
    private javax.swing.JMenuItem mnuQuanLySach;
    private javax.swing.JMenuItem mnuTTSach;
    private javax.swing.JMenuItem mnuTheDocGia;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables

    private void ButtonTabComponent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
