/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV;

import QLTV.controller.ViPhamControl;
import QLTV.helpers.MessageDialogHelper;
import QLTV.model.ViPham;
import java.util.List;

/**
 *
 * @author ngohien
 */
public class PhieuPhat extends javax.swing.JPanel {
    private MainForm parentForm;
    /**
     * Creates new form PhieuPhat
     */
    public PhieuPhat() {
        initComponents();
        
        initComBoBox();
    }

    private void initComBoBox(){
        try {
            ViPhamControl control = new ViPhamControl();
            List<ViPham> list = control.findAll();            
            cbxTenDG.removeAllItems();
            for(ViPham it : list){
                cbxTenDG.addItem(it.getHoTenDG());
            }
                
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(),"Lỗi");
            e.printStackTrace();
        }
    
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxTenDG = new javax.swing.JComboBox<>();
        btnxemchitiet = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin phiếu thu tiền phạt");

        jLabel2.setText("Tên Độc Giả: ");

        cbxTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTenDGActionPerformed(evt);
            }
        });

        btnxemchitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open-file-icon-16.png"))); // NOI18N
        btnxemchitiet.setText("Xem chi tiết");
        btnxemchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemchitietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnxemchitiet)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxemchitiet))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTenDGActionPerformed

    private void btnxemchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemchitietActionPerformed
        String HoTenDG = cbxTenDG.getSelectedItem().toString();

        ViewPhieuPhat vp = new ViewPhieuPhat(HoTenDG);
        vp.setVisible(true);
    }//GEN-LAST:event_btnxemchitietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnxemchitiet;
    private javax.swing.JComboBox<String> cbxTenDG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
