/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV;

import QLTV.controller.ThongTinSachControl;
import QLTV.helpers.DataValidator;
import QLTV.helpers.MessageDialogHelper;
import QLTV.model.ThongTinSach;
import QLTV.model.MuonTraSach;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ngohien
 */
public class QuanLyKhoSach extends javax.swing.JPanel{
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    

    /**
     * Creates new form QuanLySach
     */
    public QuanLyKhoSach() {
        initComponents();

        
        initTable();
        
        loadThongTinSach();
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã sách", "Tên sách", 
            "Thể loại", "Tác giả","Số lượng sách", "Năm xuất bản", "Nhà xuất bản","Ngày nhập",
            "Giá trị","Tình trạng"
        });
        tblQLSach.setModel(tblModel);
    }
    public void loadThongTinSach(){
        try {
            ThongTinSachControl control = new ThongTinSachControl();
            List<ThongTinSach> list = control.findAll();
            tblModel.setRowCount(0);
            for (ThongTinSach it : list) {
                tblModel.addRow(new Object[]{
                    it.getMaSach(),it.getTenSach(),it.getTheLoai(),
                    it.getTacGia(),it.getSoLuongSach(),it.getNamXuatBan(), it.getNhaXuatBan(),
                    it.getNgayNhap(),it.getGiaTri(),it.getTinhTrang()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(),"Lỗi");
        }
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtMaSachTimkiem = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNgayNhap = new javax.swing.JTextField();
        txtGiaTri = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtSoLuongSach = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        txtNhaXB = new javax.swing.JTextField();
        cmbTheLoai = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLSach = new javax.swing.JTable();
        btnNhapMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Sách");

        jLabel12.setText(" Sách:");

        txtMaSachTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachTimkiemActionPerformed(evt);
            }
        });
        txtMaSachTimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaSachTimkiemKeyReleased(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        btnTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnTimKiemKeyReleased(evt);
            }
        });

        txtTinhTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhTrangActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Sách:");

        jLabel3.setText("Tên Sách:");

        jLabel4.setText("Thể Loại:");

        jLabel5.setText("Số lượng sách");

        jLabel6.setText("Năm Xuất Bản:");

        jLabel7.setText("Nhà Xuất Bản:");

        jLabel8.setText("Ngày Nhập:");

        jLabel9.setText("Giá Trị:");

        jLabel10.setText("Tình Trạng:");

        txtMaSach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSachFocusLost(evt);
            }
        });

        cmbTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "Kiến trúc", "Kỹ năng sống" }));
        cmbTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTheLoaiActionPerformed(evt);
            }
        });

        jLabel13.setText("Tác Giả:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaTri)
                                    .addComponent(txtTinhTrang)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNhaXB, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNamXB, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSoLuongSach, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenSach, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMaSach, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNgayNhap)
                                        .addComponent(cmbTheLoai, javax.swing.GroupLayout.Alignment.LEADING, 0, 281, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cmbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuongSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhaXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        tblQLSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon16.png"))); // NOI18N
        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/luu16.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaSachTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhapMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 700, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaSachTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnNhapMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            if(txtMaSach.getText().equals("")){
                MessageDialogHelper.showMessageDialog(parentForm, "Mã sách cần phải nhập!", "Lỗi");
                return;
            }
            ThongTinSachControl control = new ThongTinSachControl();
            ThongTinSach ts = control.findByMaSach(txtMaSach.getText());
            if(ts == null){
                MessageDialogHelper.showMessageDialog(parentForm, "Mã sách không tồn tại trong bảng thông tin sách!", "Lỗi");
                return;
            } 
            if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa thông tin sách không!", "Hỏi")
                    ==JOptionPane.NO_OPTION){
                return;
            }
            if(control.deleteByMaSach(txtMaSach.getText())){
                MessageDialogHelper.showMessageDialog(parentForm, "Mã sách đã được xóa trong bảng thông tin sách!", "Thông báo");
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Mã sách không thể xóa được!", "Thông báo");
               
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtSoLuongSach.setText("");
        txtNamXB.setText("");
        txtNhaXB.setText("");
        txtNgayNhap.setText("");
        txtGiaTri.setText("");
        txtTinhTrang.setText("");
        txtTacGia.setText("");
        
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmty(txtMaSach, sb,"Mã sách không được để trống!"); 
        DataValidator.ValidateEmty(txtTenSach, sb,"Tên sách không được để trống!");  
        DataValidator.ValidateEmty(txtTacGia, sb,"Tác giả không được để trống!");        
        DataValidator.ValidateEmty(txtSoLuongSach, sb,"Số lượng sách không được để trống!");        
        DataValidator.ValidateEmty(txtNamXB, sb,"Năm xuất bản không được để trống!");        
        DataValidator.ValidateEmty(txtNhaXB, sb,"Nhà xuất bản được để trống!");        
        DataValidator.ValidateEmty(txtNgayNhap, sb,"Ngày nhập không được để trống!");        
        DataValidator.ValidateEmty(txtGiaTri, sb,"Giá trị không được để trống!");        
        DataValidator.ValidateEmty(txtTinhTrang, sb,"Tình trạng không được để trống!");        

        if(sb.length() >0){
            MessageDialogHelper.showErrorDialog(parentForm,sb.toString(), "Lỗi");
            return;
        }
        try {
            ThongTinSach ts = new ThongTinSach();
            ts.setMaSach(txtMaSach.getText());
            ts.setTenSach(txtTenSach.getText());
            ts.setTheLoai(cmbTheLoai.getSelectedItem().toString());
            ts.setNamXuatBan(Integer.parseInt(txtNamXB.getText()));
            ts.setNhaXuatBan(txtNhaXB.getText());
            ts.setNgayNhap(txtNgayNhap.getText());
            ts.setTacGia(txtTacGia.getText());
            ts.setSoLuongSach(Integer.parseInt(txtSoLuongSach.getText()));
            ts.setGiaTri(Integer.parseInt(txtGiaTri.getText()));
            ts.setTinhTrang(Integer.parseInt(txtTinhTrang.getText()));
           
            ThongTinSachControl control = new ThongTinSachControl();
            if(control.findByMaSach(txtMaSach.getText())!= null){
                if(MessageDialogHelper.showConfirmDialog(parentForm,
                        "Bạn có muốn cập nhật sách không?", "Hỏi")==JOptionPane.NO_OPTION){
                    return;
                }
                if (control.update(ts)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Sách đã được cập nhật!", "Thông báo");

                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Sách không được cập nhật do lỗi", "Cảnh báo");
                }                
            }else{
                if (control.insert(ts)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Sách đã được lưu", "Thông báo");

                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Sách không được lưu do lỗi", "Cảnh báo");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, 
                    e.getMessage(),"Lỗi");
        }        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtMaSachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSachFocusLost

    }//GEN-LAST:event_txtMaSachFocusLost

    private void txtMaSachTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachTimkiemActionPerformed

    }//GEN-LAST:event_txtMaSachTimkiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
          
       try{
            ThongTinSachControl control = new ThongTinSachControl();
            ThongTinSach ts = control.findByMaSach(txtMaSach.getText());
            tblModel.setRowCount(0);  
            if(ts!=null){
                Vector data = new Vector();
                data.add(ts.getMaSach());
                data.add(ts.getTenSach());
                data.add(ts.getTheLoai());
                data.add(ts.getTacGia());
                data.add(ts.getSoLuongSach());
                data.add(ts.getNamXuatBan());
                data.add(ts.getNhaXuatBan());
                data.add(ts.getNgayNhap());
                data.add(ts.getGiaTri());
                data.add(ts.getTinhTrang());
                
                tblModel.addRow(data);
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Không tìm thấy mã theo yêu cầu!", "Thông báo");
                loadThongTinSach();
            }
            tblQLSach.setModel(tblModel);
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        btnLuuActionPerformed(evt);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblQLSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLSachMouseClicked
        try {
            int row = tblQLSach.getSelectedRow();
            
            if(row>=0){
                String ms = (String) tblQLSach.getValueAt(row,0);
                ThongTinSachControl control= new ThongTinSachControl();
                ThongTinSach ts = control.findByMaSach(ms);
                
                if(ts!=null){
                    txtMaSach.setText(ts.getMaSach());
                    txtTenSach.setText(ts.getTenSach());
                    txtTacGia.setText(ts.getTacGia());
                    txtSoLuongSach.setText(Integer.toString(ts.getSoLuongSach()));
                    txtNhaXB.setText(ts.getNhaXuatBan());
                    txtNgayNhap.setText(ts.getNgayNhap());
                    txtTinhTrang.setText(Integer.toString(ts.getTinhTrang()));
                    txtGiaTri.setText(Integer.toString(ts.getGiaTri()));
                    txtNamXB.setText(Integer.toString(ts.getNamXuatBan()));
                    cmbTheLoai.setSelectedItem(ts.getTheLoai());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, 
                    e.getMessage(),"Lỗi");            
        }
    }//GEN-LAST:event_tblQLSachMouseClicked

    private void cmbTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTheLoaiActionPerformed

    private void btnTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTimKiemKeyReleased

    }//GEN-LAST:event_btnTimKiemKeyReleased

    private void txtMaSachTimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSachTimkiemKeyReleased
        TableRowSorter<DefaultTableModel> tra= new TableRowSorter<>(tblModel);
        
        tblQLSach.setRowSorter(tra);
        tra.setRowFilter(RowFilter.regexFilter(txtMaSachTimkiem.getText().trim()));
    }//GEN-LAST:event_txtMaSachTimkiemKeyReleased

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setVisible(true);
    }//GEN-LAST:event_formMouseExited

    private void txtTinhTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhTrangActionPerformed
        
    }//GEN-LAST:event_txtTinhTrangActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblQLSach;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMaSachTimkiem;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtNhaXB;
    private javax.swing.JTextField txtSoLuongSach;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
