/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV;

import QLTV.controller.ViPhamControl;
import QLTV.helpers.DataValidator;
import QLTV.helpers.MessageDialogHelper;
import QLTV.model.ViPham;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.NumberFormatException;

/**
 *
 * @author ngohien
 */
public class QuanLyViPham extends javax.swing.JPanel {
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    
    /**
     * Creates new form QuanLyViPham
     */
    public QuanLyViPham() {
        initComponents();

        initTable();
        
        loadDatatoTable();         
    }
        private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{ "Họ tên DG", 
            "Tiền phạt kỳ này", "Tiền nợ kỳ này", "Tổng nợ","Số tiền thu", "Tiền còn lại"}); 
        tblQLViPham.setModel(tblModel);
    }
    
    private void loadDatatoTable(){
        try {
            ViPhamControl control = new ViPhamControl();
            List<ViPham> list = control.findAll();
            tblModel.setRowCount(0);
            for (ViPham it : list) {
                tblModel.addRow(new Object[]{
                    it.getHoTenDG(),it.getTienPhatKyNay(),
                    it.getTienNoKyNay(),it.getTongNo(),
                    it.getSoTienThu(), it.getTienConLai()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(),"Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLViPham = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTienThu = new javax.swing.JTextField();
        txtHoTenDG = new javax.swing.JTextField();
        txtTienPhatKyNay = new javax.swing.JTextField();
        txtTienNoKyNay = new javax.swing.JTextField();
        txtTongNo = new javax.swing.JTextField();
        txtTienConLai = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnNhapMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Vi Phạm");

        tblQLViPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblQLViPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLViPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLViPham);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setText("Số Tiền Thu:");

        jLabel3.setText("Họ Tên Độc Giả:");

        jLabel4.setText("Tiền Phạt Kỳ Này:");

        jLabel5.setText("Tiền Nợ Kỳ Này:");

        jLabel6.setText("Tổng Nợ:");

        jLabel7.setText("Tiền Còn Lại:");

        txtTienThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienThuActionPerformed(evt);
            }
        });

        txtTienPhatKyNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienPhatKyNayActionPerformed(evt);
            }
        });

        txtTienNoKyNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienNoKyNayActionPerformed(evt);
            }
        });

        txtTongNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTongNoKeyPressed(evt);
            }
        });

        txtTienConLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienConLaiActionPerformed(evt);
            }
        });
        txtTienConLai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienConLaiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTongNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(txtTienNoKyNay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienPhatKyNay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTenDG, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienThu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTienConLai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTenDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(txtTienPhatKyNay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTienNoKyNay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTongNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTienThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienConLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon16.png"))); // NOI18N
        btnNhapMoi.setText("Nhập Mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/luu16.png"))); // NOI18N
        btnLuu.setText("Lưu ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNhapMoi)
                .addGap(33, 33, 33)
                .addComponent(btnLuu)
                .addGap(32, 32, 32)
                .addComponent(btnCapNhat)
                .addGap(37, 37, 37)
                .addComponent(btnXoa)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        txtTienThu.setText("");
        txtHoTenDG.setText("");
        txtTienPhatKyNay.setText("");
        txtTienNoKyNay.setText("");
        txtTongNo.setText("");
        txtTienConLai.setText("");
        
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmty(txtTienThu, sb,"Số tiền thu không được để trống");
        DataValidator.ValidateEmty(txtTienConLai, sb,"Tiền còn lại không được để trống");
        DataValidator.ValidateEmty(txtHoTenDG, sb,"Họ tên độc giả không được để trống");
        DataValidator.ValidateEmty(txtTienPhatKyNay, sb,"Tiền phạt kỳ này không được để trống");
        DataValidator.ValidateEmty(txtTienNoKyNay, sb,"Tiền nợ kỳ này không được để trống");
        DataValidator.ValidateEmty(txtTongNo, sb,"Tổng nợ không được để trống");
        
        if(sb.length() >0){
            MessageDialogHelper.showErrorDialog(parentForm,sb.toString(), "Lỗi");
            return;
        }
        try {
            ViPham vp = new ViPham();
            vp.setHoTenDG(txtHoTenDG.getText());
            vp.setSoTienThu(Integer.parseInt(txtTienThu.getText()));
            vp.setTienPhatKyNay(Integer.parseInt(txtTienPhatKyNay.getText()));
            vp.setTienNoKyNay(Integer.parseInt(txtTienNoKyNay.getText()));
            vp.setTongNo(Integer.parseInt(txtTongNo.getText()));
            vp.setTienConLai(Integer.parseInt(txtTienConLai.getText()));

            ViPhamControl control = new ViPhamControl();
            if(control.insert(vp)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin độc giả vi phạm đã được lưu", "Thông báo");
                loadDatatoTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Thông tin độc giả vi phạm không được lưu do lỗi", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, 
                    e.getMessage(),"Lỗi");
        }        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmty(txtTienThu, sb,"Số tiền thu không được để trống");
        DataValidator.ValidateEmty(txtTienConLai, sb,"Tiền còn lại không được để trống");
        DataValidator.ValidateEmty(txtHoTenDG, sb,"Họ tên độc giả không được để trống");
        DataValidator.ValidateEmty(txtTienPhatKyNay, sb,"Tiền phạt kỳ này không được để trống");
        DataValidator.ValidateEmty(txtTienNoKyNay, sb,"Tiền nợ kỳ này không được để trống");
        DataValidator.ValidateEmty(txtTongNo, sb,"Tổng nợ không được để trống");
  
        if(sb.length() >0){
            MessageDialogHelper.showErrorDialog(parentForm,sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, 
                "Bạn có muốn cập nhật thông tin vi phạm sách không?", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
            ViPham vp = new ViPham();
            vp.setHoTenDG(txtHoTenDG.getText());
            vp.setSoTienThu(Integer.parseInt(txtTienThu.getText()));
            vp.setTienPhatKyNay(Integer.parseInt(txtTienPhatKyNay.getText()));
            vp.setTienNoKyNay(Integer.parseInt(txtTienNoKyNay.getText()));
            vp.setTongNo(Integer.parseInt(txtTongNo.getText()));
            vp.setTienConLai(Integer.parseInt(txtTienConLai.getText()));

            ViPhamControl control = new ViPhamControl();
            if(control.update(vp)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin độc giả vi phạm đã được cập nhật!", "Thông báo");
                loadDatatoTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Thông tin độc giả vi phạm không được cập nhật do lỗi!", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, 
                    e.getMessage(),"Lỗi");
        } 
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmty(txtHoTenDG, sb,"Số tiền thu không được để trống");

        if(sb.length() >0){
            MessageDialogHelper.showErrorDialog(parentForm,sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, 
                "Bạn có chắc muốn xóa thông tin độc giả vi phạm sách không?", "Hỏi")==JOptionPane.NO_OPTION){
            return;
        }
        try {
            ViPhamControl control = new ViPhamControl();
            if(control.delete(txtHoTenDG.getText())){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin độc giả vi phạm sách được xóa", "Thông báo");
                btnTaoMoiActionPerformed(evt);
                loadDatatoTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Thông tin độc giả vi phạm sách không được xóa do lỗi", "Cảnh báo");
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(parentForm, 
                    e.getMessage(),"Lỗi");
        } 
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblQLViPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLViPhamMouseClicked
        try {
            int row = tblQLViPham.getSelectedRow();
            
            if(row>=0){
                String id = (String) tblQLViPham.getValueAt(row,0);
                ViPhamControl control = new ViPhamControl();
                ViPham vp = control.findByHoTenDG(id);
                
                if(vp!=null){
                    txtHoTenDG.setText(vp.getHoTenDG());
                    txtTienThu.setText(Integer.toString(vp.getSoTienThu()));
                    txtTienConLai.setText(Integer.toString(vp.getTienConLai()));
                    txtTienPhatKyNay.setText(Integer.toString(vp.getTienPhatKyNay()));
                    txtTienNoKyNay.setText(Integer.toString(vp.getTienNoKyNay()));
                    txtTongNo.setText(Integer.toString(vp.getTongNo()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(),"Lỗi");            
        }
    }//GEN-LAST:event_tblQLViPhamMouseClicked

    private void txtTienPhatKyNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienPhatKyNayActionPerformed
        
    }//GEN-LAST:event_txtTienPhatKyNayActionPerformed

    private void txtTienNoKyNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienNoKyNayActionPerformed
    }//GEN-LAST:event_txtTienNoKyNayActionPerformed

    private void txtTongNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongNoKeyPressed
        int TongNo;
        int TienPhatKyNay= Integer.parseInt(txtTienPhatKyNay.getText());
        int TienNoKyNay = Integer.parseInt(txtTienNoKyNay.getText());
        TongNo= TienPhatKyNay +TienNoKyNay;
        txtTongNo.setText(Integer.toString(TongNo));
    }//GEN-LAST:event_txtTongNoKeyPressed

    private void txtTienConLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienConLaiActionPerformed

    }//GEN-LAST:event_txtTienConLaiActionPerformed

    private void txtTienThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienThuActionPerformed
        int TienThu = Integer.parseInt(txtTienThu.getText());
    }//GEN-LAST:event_txtTienThuActionPerformed

    private void txtTienConLaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienConLaiKeyPressed
        int TienConLai;
        int TienThu = Integer.parseInt(txtTienThu.getText());
        int TongNo = Integer.parseInt(txtTongNo.getText());
        TienConLai = TienThu - TongNo;
        txtTienConLai.setText(Integer.toString(TienConLai));
    }//GEN-LAST:event_txtTienConLaiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblQLViPham;
    private javax.swing.JTextField txtHoTenDG;
    private javax.swing.JTextField txtTienConLai;
    private javax.swing.JTextField txtTienNoKyNay;
    private javax.swing.JTextField txtTienPhatKyNay;
    private javax.swing.JTextField txtTienThu;
    private javax.swing.JTextField txtTongNo;
    // End of variables declaration//GEN-END:variables

    private void btnTaoMoiActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
